name: APP Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}   

jobs:
  deploy:
    runs-on: ubuntu-latest    

    steps:
      # 1️ Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2️ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3 Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
       # 4 Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t app project8-website
          docker tag app:latest ${{ secrets.ECR_REPOSITORY }}:latest

      # 5 Push Image
      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

       # 6 Update ECS Service
      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment
